### ISSUE TITLE
Update to latest version of boostrap 3: 3.3.7

### ISSUE THREAD

**Issue by evilaliv3** [MohammadYounes/RTL-bootstrap#10]
Hello @MohammadYounes 

In [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) we are still using bootstrap 3.

Would you please support us releasing a version of bootstrap-inline-rtl aligned to the latest version of boostrap 3.3.7

Thank you so much!

**Comment by MohammadYounes** [comment]
Hey @evilaliv3 

Sure, added to my todo list!

**Comment by MohammadYounes** [comment]
@evilaliv3  3.3.7 Available on npm!

**Comment by evilaliv3** [comment]
Thank you @MohammadYounes !
