### ISSUE TITLE
RTL responsive table not x scroll

### ISSUE THREAD

**Issue by manisi** [MohammadYounes/RTL-bootstrap#6]
Hi,Mohammd
thanks to rtl css.
but in rtl table in mobile device not  responsive (not x scroll).
in ltr dir  is ok.
please help me for responsive table  RTL in mobile device .
see this code:

```html
   <div class="table-responsive">
        <table class="jh-table table table-striped">
            <thead>
                <tr jh-sort="vm.predicate" ascending="vm.reverse" callback="vm.reset()">
                    <th jh-sort-by="id"><span translate="global.field.id">ID</span> <span class="glyphicon glyphicon-sort"></span></th>
                    <th jh-sort-by="fname"><span translate="personelArchiverApp.personel.fname">Fname</span> <span class="glyphicon glyphicon-sort"></span></th>
                    <th jh-sort-by="lnam"><span translate="personelArchiverApp.personel.lnam">Lnam</span> <span class="glyphicon glyphicon-sort"></span></th>
                    <th jh-sort-by="bdate"><span translate="personelArchiverApp.personel.bdate">Bdate</span> <span class="glyphicon glyphicon-sort"></span></th>
                    <th jh-sort-by="faal"><span translate="personelArchiverApp.personel.faal">Faal</span> <span class="glyphicon glyphicon-sort"></span></th>
                    <th></th>
                </tr>
            </thead>
            <tbody infinite-scroll="vm.loadPage(vm.page + 1)" infinite-scroll-disabled="vm.page >= vm.links['last']">
                <tr ng-repeat="personel in vm.personels track by personel.id">
                    <td><a ui-sref="personel-detail({id:personel.id})">{{personel.id}}</a></td>
                    <td>{{personel.fname}}</td>
                    <td>{{personel.lnam}}</td>
                        <td>{{personel.bdate | date:'mediumDate'}}</td>
                    <td>{{personel.faal}}</td>
````

**Comment by MohammadYounes** [comment]
Hi, Would you create an online demo to investigate this?

**Comment by manisi** [comment]
not uploaded ..
in localhost ..

**Comment by MohammadYounes** [comment]
Just create a sample presenting the issue!

**Comment by MohammadYounes** [comment]
I see no problem here, see https://jsfiddle.net/fsqow546/

**Comment by manisi** [comment]
Thanks Mohammad .
this problem.

**Comment by MohammadYounes** [comment]
what problem ?

**Comment by manisi** [comment]
in my sample code html dir is rtl.
when resize page to small table data not scrolled.

**Comment by MohammadYounes** [comment]
Still the same https://jsfiddle.net/fsqow546/2/, Seems its related to another component you are using!

**Comment by manisi** [comment]
<!doctype html>
<html dir="rtl" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>personelArchiverApp</title>
    <meta name="description" content="">
    <meta name="google" value="notranslate">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="bower_components/angular-loading-bar/build/loading-bar.css" />
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.rtl.css" />
    <link rel="stylesheet" href="content/css/main.css">
</head>
<body ng-app="personelArchiverApp">

**Comment by manisi** [comment]
<!doctype html>
<html dir="rtl" class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>personelArchiverApp</title>
    <meta name="description" content="">
    <meta name="google" value="notranslate">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="bower_components/angular-loading-bar/build/loading-bar.css" />
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.rtl.css" />
    <link rel="stylesheet" href="content/css/main.css">
</head>
<body ng-app="personelArchiverApp">

**Comment by MohammadYounes** [comment]
Would join me here https://gitter.im/MohammadYounes/RTL-bootstrap ?
