### ISSUE TITLE
Change package naming in package.json and bower.json and release as bower package

### ISSUE THREAD

**Issue by evilaliv3** [MohammadYounes/RTL-bootstrap#8]
A package name should be identified for this specialized version of bootstrap (rtl-bootstrap? antani?) and the package be released on bower.

The new name should be written in:
- package.json
- bower.json

Then in order to release the project it should be published on:
- https://www.npmjs.com following guide: https://docs.npmjs.com/getting-started/publishing-npm-packages
- http://bower.io following guide: http://bower.io/docs/creating-packages/

This way other users (GlobaLeaks) would be able to use that! :)

**Comment by MohammadYounes** [comment]
@evilaliv3 I don't expect much updates on this. Anyhow, it's published under the name `bootstrap-inline-rtl`


#### Install via Bower
```
bower install bootstrap-inline-rtl
``` 

#### Install via NPM

```
npm install bootstrap-inline-rtl
```
