### ISSUE TITLE
Verify if the current set of changes is valid for Bootstrap 4 and release an update package

### ISSUE THREAD

**Issue by evilaliv3** [MohammadYounes/RTL-bootstrap#9]
Hi @MohammadYounes, would you please verify if the scripts yo were using for making possible to use Bootstrap in RTL websites could work against the version 4  or guide me to do that?

that would be really important for the globaleaks project! :)

**Comment by MohammadYounes** [comment]
Hi @evilaliv3, I have already converted v4. Hopefully, I'll publish it by the weekend!

**Comment by evilaliv3** [comment]
fantastic @MohammadYounes !

**Comment by MohammadYounes** [comment]
@evilaliv3 Just published [v4-rtl](https://github.com/RTLCSS/bootstrap/tree/v4-rtl). You can preview it at http://bootstrap.rtlcss.com/
